# .github/workflows/deploy.yaml
name: Deploy to Cloud Run using Cloud Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    # サービスアカウントキー方式ではid-tokenは不要です
    permissions:
      contents: 'read'
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # (デバッグ用のステップは、もう不要なので削除して構いません)

      # 2. Google Cloudへの認証 (サービスアカウントキー方式)
      # ★★★ ここが重要な変更点 ★★★
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          
      # 3. gcloudコマンドラインツールをセットアップ
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: 'oceanic-camera-465821-r2'

      # 4. gcloudコマンドを使ってCloud Buildを直接実行
      - name: Run Cloud Build
        run: gcloud builds submit . --config=cloudbuild.yaml
